services:
  - type: web
    name: tabpy-server
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      echo admin:admin > passwords
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT --timeout 180
    envVars:
      - key: PORT
        value: 9004
