services:
  - type: web
    name: tabpy-server
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      echo "$TABPY_PASSWORD_ENTRY" > passwords.txt
      gunicorn wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 9004
      - key: TABPY_PASSWORD_ENTRY
        value: admin:admin
